// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChannelMessageAttachment } from "./ChannelMessageAttachment";
import type { JsonValue } from "./serde_json/JsonValue";

export type ChannelMessageEvent = { id: string, schemaVersion: number, server: string, source: string | null, sender: string | null, text: string, attachments?: Array<ChannelMessageAttachment>, metadata: JsonValue | null, };
