// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ChannelMessageAttachment = { kind: string, path?: string, mimeType?: string, fileName?: string, fileSize?: bigint, metadata?: JsonValue, };
