// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type ChannelMessageAttachment = { kind: string, path?: string | null, mimeType?: string | null, fileName?: string | null, fileSize?: bigint | null, metadata?: JsonValue | null, };
